### ISSUE TITLE
Execute a single action directly and compare the results

### ISSUE THREAD

**Issue by U-lis** [planetarium/NineChronicles.Headless#1628]
Related issues: https://github.com/planetarium/NineChronicles.Headless/issues/1632

# Small step(4 inch reflector)

Before checking the block unit result, check the action unit result first.

- Use a json format source such as 'Actions' included in the transaction.
- The user can get the result of executing an action of type [IAccountStateView][iaccountstateview-link] or [IAccountStateDelta][iaccountstatedelta-link].

[iaccountstateview-link]: https://github.com/planetarium/libplanet/blob/main/Libplanet/Action/IAccountStateView.cs
[iaccountstatedelta-link]: https://github.com/planetarium/libplanet/blob/main/Libplanet/Action/IAccountStateDelta.cs

## Expect use case

1. Prepare blockchain store.
2. Prepare actions.(e.g., actions.json file)
3. Checkout specific version of lib9c(e.g., v100300).
4. Run action execute cli with specific block index.
   - Get action result as IAccountStateView or IAccountStateDelta.
6. Checkout another specific version of lib9c(e.g., v100400).
7. Run action execute cli with specific block index.
   - get action result as IAccountStateView or IAccountStateDelta.
8. Compare action results of step 4 and 6.

## Actions example

```json
[
  {
    "type_id": "buy3",
    "values": {
      "buyerAvatarAddress": "e33159240ec8b6b074fe4da27f760dedb41fdb55",
      "id": "1a16a1a035d84944bc764790f12a4b5a",
      "productId": "36c9a95b064df344b4c7965352147404",
      "sellerAgentAddress": "f189c04126e2e708cd7d17cd68a7b7f10bbb6f16",
      "sellerAvatarAddress": "cc2570cff8aea5f9d907552c95d452aded8818d9",
    },
  }
]
```

## CLI example

```
dotnet run NineChronicles.Headless.executable action execute \
  --actions=[str] \
  --block-index=[long=TIP] \
  --store-type=[str="rocksdb"] \
  --strore-path=[str="DEFAULT_PATH"] \
  --verbose=[bool=false]
```

# Things to consider

- If it helps, consider using [Telescope](https://github.com/planetarium/Telescope) to get transactions and actions information included in a specific block.

# Todo

- [x] Implement subcommand(action execute)
   - [x] Load blockchain store by block index
   - [x] Create transaction from `txPath` param
   - [x] Execute transaction based on loaded blockchain store
   - [x] Verbose output(updated addresses and updated states)
